# Generated by Django 4.0.3 on 2023-04-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms_rest', '0002_rename_title_workout_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='exercise',
            field=models.ManyToManyField(to='gyms_rest.exercise'),
        ),
    ]
