# Generated by Django 4.0.3 on 2023-04-25 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms_rest', '0003_workout_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='UserVO',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
